site_name: Mapzen Android SDK
docs_dir: src-android
site_dir: dist-android

pages:
  - Home: index.md
  - 'Installation': 'installation.md'
  - 'Get started': 'getting-started.md'
  - 'Current location': 'current-location.md'
  - 'Position, rotation, and zoom': 'basic-functions.md'
  - 'Markers': 'markers.md'
  - 'Polylines': 'polyline.md'
  - 'Polygons': 'polygon.md'
  - 'Switching styles': 'styles.md'
  - 'Gesture responders': 'gesture-responders.md'
  - 'Location services': 'location-services.md'
  - 'Mapzen Search': 'search.md'
  - 'Mapzen Turn-by-Turn': 'turn-by-turn.md'

extra:
  site_subtitle: 'A thin wrapper that packages up everything you need to use Mapzen services in your Android applications.'
  project_repo_url: https://github.com/mapzen/android
  docs_base_url: https://github.com/mapzen/android/tree/master/docs
