site_name: Cartography
#docs_dir: src-cartography
docs_dir: src-cartography-new
site_dir: dist-cartography

pages:
  - Home: index.md
  - 'Get started': 'get-started.md'
  - 'API reference': 'api-reference.md'
  - 'Basemap styles': 'styles.md'
  - 'Icons': 'icons.md'
  - 'Versioning': 'versioning.md'

extra:
  site_subtitle: 'Get everything you need to use Mapzen basemaps and icons in your applications.'
  project_repo_url: https://github.com/tangrams/cartography-docs
  docs_base_url: https://github.com/tangrams/cartography-docs/master
