site_name: Elevation Service
docs_dir: src/elevation
site_dir: dist/elevation
include_next_prev: false
extra_css: [css/codehilite/mapzen.css]

pages:
  - Home: index.md
  - 'Elevation service': 'elevation-service.md'

extra:
  site_subtitle: 'Take your map to new heights.'
  project_repo_url: https://github.com/valhalla/skadi
  docs_base_url: https://github.com/valhalla/valhalla-docs/tree/matrix-help
