site_name: Developer Guides
docs_dir: src-guides
site_dir: dist-guides

pages:
  - Home: 'index.md'
  - Text editors: 'install-text-editor.md'
  - Server environment: 'server-environment.md'

extra:
  site_subtitle: 'Set up your development environment with these how-to topics'
  project_repo_url: https://github.com/mapzen/mapzen-docs-generator
  docs_base_url: https://github.com/mapzen/mapzen-docs-generator/tree/master/docs
