site_name: Mapzen Search
docs_dir: src-search
site_dir: dist-search

pages:
  - Home: index.md
  - 'Get started': 'get-started.md'
  - 'Add search to a map': 'add-search-to-a-map.md'
  - 'API keys and rate limits': 'api-keys-rate-limits.md'
  - 'Search': 'search.md'
  - 'Reverse geocoding': 'reverse.md'
  - 'Autocomplete': 'autocomplete.md'
  - 'Place': 'place.md'
  - 'API responses': 'response.md'
  - 'Data sources': 'data-sources.md'
  - 'Load data from the browser': 'use-cors.md'
  - 'Terminology': 'glossary.md'
  - 'HTTP status codes': 'http-status-codes.md'
  - 'Transition from Pelias beta': 'transition-from-beta.md'
  - 'Release notes': 'release-notes.md'

extra:
  site_subtitle: 'Find places and addresses with this geographic search service built on open tools and open data.'
  #'High-performance geocoding and place search service'
  project_repo_url: https://github.com/pelias/
  docs_base_url: https://github.com/pelias/pelias-doc/blob/master
