site_name: Mapzen Search
docs_dir: src-search
site_dir: dist-search

pages:
  - Home: index.md
  - 'Glossary': 'glossary.md'
  - 'Search': 'search.md'
  - 'Reverse geocoding': 'reverse.md'
  - 'Autocomplete': 'autocomplete.md'
  - 'Place': 'place.md'
  - 'Tutorial': 'add-search-to-a-map.md'
  - 'API responses': 'response.md'
  - 'Data sources': 'data-sources.md'
  - 'Load data from the browser': 'use-cors.md'
  - 'HTTP status codes': 'http-status-codes.md'
  - 'API keys and rate limits': 'api-keys-rate-limits.md'
  - 'Release notes': 'release-notes.md'

mz:redirects:
  'get-started': '.'

extra:
  site_subtitle: 'Find places and addresses with this geographic search service built on open tools and open data.'
  project_repo_url: https://github.com/pelias/
  docs_base_url: https://github.com/pelias/pelias-doc/blob/master
