site_name: Tangram
repo_url: https://github.com/tangrams/tangram
remote_branch: gh-pages
google_analytics: ['UA-47035811-1', 'mapzen.com']
docs_dir: src/tangram
theme: mkdocs
theme_dir: theme
site_dir: dist/tangram
include_nav: true
include_next_prev: true

# Because Tangram does not organize documentation in folders, we're going to have
# to enforce the Table of Contents structure manually in the configuration below.
# This means pages should be added or subtracted manually here if the files change.
pages:
  - Home: index.md
  - Concept Overviews:
    - 'The Scene File': 'Scene-file.md'
    - 'Filters': 'Filters-Overview.md'
    - 'Lights': 'Lights-Overview.md'
    - 'Cameras': 'Cameras-Overview.md'
    - 'Materials': 'Materials-Overview.md'
    - 'Shaders': 'Shaders-Overview.md'
    - 'Styles': 'Styles-Overview.md'
  - Technical Reference:
    - 'yaml': 'yaml.md'
    - 'scene': 'scene.md'
    - 'sources': 'sources.md'
    - 'cameras': 'cameras.md'
    - 'lights': 'lights.md'
    - 'materials': 'materials.md'
    - 'styles': 'styles.md'
    - 'layers': 'layers.md'
    - 'draw': 'draw.md'
    - 'shaders': 'shaders.md'

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: false

markdown_extensions:
  - smarty
  - toc:
      permalink: ' ' # Blank space; this marker is styled in CSS.
  - sane_lists
  - nl2br
  - linkify

# Extra variables for templates
extra:
  docs_repo_url: https://github.com/tangrams/tangram-docs
  display_project_name_api_key: true
  exclude_home_contents_in_toc: true
