site_name: Mapzen Turn-by-Turn
docs_dir: src/turn-by-turn
site_dir: dist/turn-by-turn
extra_css: [css/codehilite/mapzen.css]

pages:
  - Home: index.md
  - 'API Reference': 'api-reference.md'
  - 'Terminology': 'terminology.md'
  - 'Add Mapzen Turn-by-Turn routing to a map': 'add-routing-to-a-map.md'

extra:
  site_subtitle: 'Add routing and navigation to your web and mobile apps.'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/mapzen/mapzen-docs/tree/master/turn-by-turn
