site_name: Vector Tile Service
docs_dir: src-vector-tiles
site_dir: dist-vector-tiles

pages:
  - Home: index.md
  - 'Layers': 'layers.md'
  - 'Get started': 'use-service.md'
  - 'Make a map': 'display-tiles.md'
  - 'Data sources': 'data-sources.md'
  - 'Migrate to version 1.0': 'migrate-to-vector-tiles-v1.md'
  
mz:redirects:
  'attribution': '.'
  'api-keys-and-rate-limits': '.'

# Extra variables for templates
extra:
  site_subtitle: 'Add open geospatial data to your applications with the vector tile map service.'
  project_repo_url: https://github.com/tilezen/vector-datasource
  docs_base_url: https://github.com/tilezen/vector-datasource/tree/master/docs
  exclude_home_contents_in_toc: false
