site_name: Vector Tile Service
docs_dir: src/vector-tiles
site_dir: dist/vector-tiles

pages:
  - Home: index.md
  - 'Get started': 'use-service.md'
  - 'Make a map': 'display-tiles.md'
  - 'Layers': 'layers.md'

# Extra variables for templates
extra:
  site_subtitle: 'Add open geospatial data to your applications with the vector tile map service.'
  project_repo_url: https://github.com/mapzen/vector-datasource
  docs_base_url: https://github.com/mapzen/mapzen-docs/tree/master/vector-tiles
  exclude_home_contents_in_toc: false
